services:

  app:
    image: transport_integration:v0.1
    container_name: transport_integration
    env_file:
      - .env
    ports:
      - "8101:8101"
    volumes:
      - ./:/app
      - dev-logs:/logs/
    restart: always
    command: >
      sh -c "python main.py"

volumes:
  dev-logs: